config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
  post 'login', to: "authentication#login"
  get 'logout', to: 'authentication#logout'
  get 'search', to: "patients#search"
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :name, presence: true
    validates :dob, presence: true
    validates :email, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate

  include ApplicationHelper
  include ActionController::Cookies

  rescue_from JWT::VerificationError, with: :invalid_token
  rescue_from JWT::DecodeError, with: :decode_error

  private

  def authenticate
    # p request.headers['Authorization']
    # authorization_header = request.headers['Authorization']
    # token = authorization_header.split(" ").last if authorization_header
    # decoded_token = JsonWebToken.decode(token)
    # user_id = JsonWebToken.decode(token)[:user_id]
    # expires_at = JsonWebToken.decode(token)[:exp]
  
    @user = User.find_by(id: session[:user_id])
    if @user.blank?
      flash[:alert] = 'Unauthorized request'
      redirect_to root_path
    else
      current_user
    end
  end
  
  def invalid_token
    render json: { invalid_token: 'invalid token' }
  end
  
  def decode_error
    render json: { decode_error: 'decode error' }
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
    skip_before_action :authenticate
 
    def login
      user = User.find_by(email: params[:email])
      authenticated_user = user&.authenticate(params[:password])
   
      if authenticated_user
        session[:user_id] = user.id
        # token = JsonWebToken.encode(user_id: user.id)
        # expires_at = JsonWebToken.decode(token)[:exp]
        flash[:success] = 'Congratulations! you are login successfully.'
        redirect_to patients_path
      else
        flash[:danger] = "Please check the login details."
        redirect_to root_path
      end
    end

    def logout
      session[:user_id] = nil
      flash[:success] = 'Congratulations! you are logged out successfully.'
      redirect_to root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authenticate

    def index
        redirect_to patients_path if current_user
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def search
        if params[:query].present?
            @patients = Patient.where('name =? OR email=?', params[:query], params[:query])
        else
            @patients = Patient.all
        end
        @patients = @patients.paginate(page: params[:page], per_page: 2)
        render :index
    end

    def index
        if params[:type].present? && params[:type] == 'upcoming'
            @patients = Patient.where('next_appointment_date >=? AND next_appointment_date <=?', Time.now, Time.now + 72.hours)
        else
            @patients = Patient.all
        end
        @patients = @patients.paginate(page: params[:page], per_page: 2)
        p @patients
    end

    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.new(patient_params)
        if @patient.save
            flash[:success] = 'Patient record has been created successfully.'
            redirect_to patients_path
        else
            flash[:danger] = 'Patient record cannot be saved. Please check the errors below.'
            render :new
        end
    end

    def edit
        @patient = Patient.find_by(id: params[:id])
    end

    def update
        @patient = Patient.find_by(id: params[:id])
        if @patient.update(patient_params)
            flash[:success] = 'Patient details have been updated successfully.'
            redirect_to patients_path
        else
            flash[:danger] = 'Patient details cannot be updated.'
            render :edit
        end
    end

    private

    def patient_params
        params.require(:patient).permit(:name, :email, :dob, :next_appointment_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/home/index.html.erb
<div class="container" style="padding: 100px 0px">
    <div class='row justify-content-md-center'>
        <div class='col-md-6'>
            <div class='card'>
                <div class="card-body">
                    <h5 class="card-title mb-3">Login Details</h5>
                    <%= form_tag "/login", method: "post" do %>
                        <div class="mb-3">
                            <%= text_field_tag :email, params[:email], class: 'form-control', id: 'exampleInputEmail1', placeholder: 'Email' %>
                        </div>
                        <div class="mb-3">
                            <%= password_field_tag :password, params[:password], class: 'form-control', id: 'exampleInputPassword1', placeholder: 'Password' %>
                        </div>
                        <%= submit_tag 'Login', class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">PatientApp</a>
        <div class="d-flex flex-row">
            <% if current_user.present? %>
                <span class="navbar-text" style="margin-right: 10px">
                    <%= current_user&.email %>
                </span>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href='/logout'>Logout</a>
                    </li>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Patient App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>  
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>  
    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"></script>
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>
    
    
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"> %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel ="stylesheet" href ="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %> 
    <%= render 'layouts/flash' %> 
    <%= yield %>
    <script type="text/javascript">
      $(function () {
        $('#inputAppointment').datetimepicker({
          format: 'DD-MM-YYYY HH:mm:ss'
        });
      });
    </script>
  </body>
</html>

app/views/patients/_patient.html.erb
    <tr>
        <td><%= patient.name %></td>
        <td><%= link_to patient.email, edit_patient_path(patient) %></td>
        <td><%= patient.next_appointment_date.strftime("%d/%m/%y: %H:%M:%S %Z") %></td>
    </tr>

app/views/patients/edit.html.erb
<div class='container' style="padding: 100px 0px">
    <div class="mb-3 row">
        <h3>Edit Patient</h3>
    </div>
    <%= form_for @patient do |f| %>
        <div class="mb-3 row">
            <label for="inputName" class="col-sm-2 col-form-label">Name*:</label>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control", id:"inputName", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputEmail" class="col-sm-2 col-form-label">Email*:</label>
            <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control", id: "inputEmail", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputDOB" class="col-sm-2 col-form-label">Date of Birth*:</label>
            <div class="col-sm-10">
                <%= f.text_field :dob, class: "form-control", id: "inputDOB", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputAppointment" class="col-sm-2 col-form-label">Next Appointment:</label>
            <div class="col-sm-10" style="position: relative">
                <%= f.text_field :next_appointment_date, class: "form-control", id: "inputAppointment" %>
            </div>
        </div>
        <% if @patient.errors.any? %>
            <ul>
                <% @patient.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
         <div class="mb-3">
            <%= f.submit 'Save', class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/patients/index.html.erb
<div class='container' style="padding: 100px 0px">
    <div class='mb-3 row'>
        <div class='col-md-12'>
            <%= form_with url: "/search", method: :get do |form| %>
                <%= form.search_field :query, placeholder: 'Search by name/email', class: 'form-control' %>
            <% end %>
        </div>
    </div>
    <div class='mb-3 row'>
        <div class='col-md-12'>
            <p class="fs-1 fw-bold float-start">
                Patients 
                <a class='btn btn-primary' href=<%= new_patient_path %>>New Patient</a>
            </p>
            <p class="fs-1 fw-bold float-end">
                <a class='btn btn-secondary' href=<%= patients_path(type: 'upcoming') %>>Upcoming</a>
            </p>
        </div>
    </div>
    <div class='mb-3 row'>
        <div class='col-md-12'>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Next Appointment</th>
                    </tr>
                </thead>
                <%= will_paginate @patients %>
                <%= render @patients %>
            </table>
            <% if @patients.count == 0 %>   
                <h5>No Patient record is present.</h5>
            <% end %>
        </div>
    </div>
</div>

app/views/patients/new.html.erb
<div class='container' style="padding: 100px 0px">
    <div class="mb-3 row">
        <h3>Add Patient</h3>
    </div>
    <%= form_for @patient do |f| %>
        <div class="mb-3 row">
            <label for="inputName" class="col-sm-2 col-form-label">Name*:</label>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control", id:"inputName", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputEmail" class="col-sm-2 col-form-label">Email*:</label>
            <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control", id: "inputEmail", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputDOB" class="col-sm-2 col-form-label">Date of Birth*:</label>
            <div class="col-sm-10">
                <%= f.text_field :dob, class: "form-control", id: "inputDOB", required: true %>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputAppointment" class="col-sm-2 col-form-label">Next Appointment:</label>
            <div class="col-sm-10" style="position: relative">
                <%= f.text_field :next_appointment_date, class: 'form-control', id: 'inputAppointment' %>
            </div>
        </div>
        <% if @patient.errors.any? %>
            <ul>
                <% @patient.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
        <div class="mb-3">
            <%= f.submit 'Create', class: "btn btn-primary" %>
        </div>
    <% end %>
</div>